Update aws_cd.yml to deploy on new account

diff --git a/.github/workflows/aws_cd.yml b/.github/workflows/aws_cd.yml
--- a/.github/workflows/aws_cd.yml
+++ b/.github/workflows/aws_cd.yml
@@ -14,16 +14,39 @@ jobs:
       contents: read
     steps:
         - uses: actions/checkout@v2
-        - name: Setup AWS Credentials
-          uses: aws-actions/configure-aws-credentials@v2
-          with:
-            aws-region: sa-east-1
-            role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubActionsRole
-            role-session-name: github-action
-        - name: Use Node.js 18.x
+        - name: Determine AWS account ID
+          run: |
+            if [[ "${{ github.ref_name }}" == "dev" ]]; then
+              echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_DEV }}" >> $GITHUB_ENV
+            elif [[ "${{ github.ref_name }}" == "homolog" ]]; then
+              echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_HOMOLOG }}" >> $GITHUB_ENV
+            elif [[ "${{ github.ref_name }}" == "prod" ]]; then
+              echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_PROD }}" >> $GITHUB_ENV
+            else
+              echo "Invalid branch name!" && exit 1
+            fi
+            echo "AWS_REGION=us-east-1" >> $GITHUB_ENV
+
+        - name: Use Node.js 22.x
           uses: actions/setup-node@v3
           with:
-            node-version: 18.x
+            node-version: 22.x
+
+        - name: Install AWS CDK
+          run: npm install -g aws-cdk
+  
+        - name: Setup AWS Credentials
+          id: aws-credentials
+          uses: aws-actions/configure-aws-credentials@v2
+          with:
+            aws-region: us-east-1
+            role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/GithubActionsRole
+            role-session-name: github-action
+            role-duration-seconds: 3600
+        - name: Use Node.js 22.x
+          uses: actions/setup-node@v3
+          with:
+            node-version: 22.x
         - name: Setting stage and stack name
           run: |
             echo "STAGE=${{ github.ref_name }}" 
@@ -48,17 +71,12 @@ jobs:
             npm run build
         - name: Setup envs
           run: |
-            echo AWS_REGION=sa-east-1 >> $GITHUB_ENV
-            echo AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }} >> $GITHUB_ENV
+            echo AWS_REGION=us-east-1 >> $GITHUB_ENV
+            echo AWS_ACCOUNT_ID=${{ env.AWS_ACCOUNT_ID }} >> $GITHUB_ENV
             echo STACK_NAME=${{ env.STACK_NAME }} >> $GITHUB_ENV
             echo GITHUB_REF_NAME=${{ github.ref_name }} >> $GITHUB_ENV
             echo ACM_CERTIFICATE_ARN=${{ secrets.DEVMAUA_ACM_CERTIFICATE_ARN }} >> $GITHUB_ENV
-            echo HOSTED_ZONE_ID=${{ secrets.DEVMAUA_HOSTED_ZONE_ID }} >> $GITHUB_ENV
-            if [ -z "${{ vars.ALTERNATIVE_DOMAIN_NAME }}" ]; then
-              echo ALTERNATIVE_DOMAIN_NAME=$(echo ${{ env.PROJECT_NAME }} | tr '[:upper:]' '[:lower:]').devmaua.com >> $GITHUB_ENV
-            else
-              echo ALTERNATIVE_DOMAIN_NAME=${{ vars.ALTERNATIVE_DOMAIN_NAME }} >> $GITHUB_ENV
-            fi
+           
             
             echo ${{ env.AWS_REGION }}
             echo ${{ env.AWS_ACCOUNT_ID }}
